### ISSUE TITLE
Spark 2.1.0 package not found

### ISSUE THREAD

**Issue by quartox** [groupon/sparklint#53]
There is a commit message visible from the github page that says `Support spark 2.1.0` but the sparklint package for spark version 2.1.0 cannot be found when submitting the spark job.

**Comment by roboxue** [comment]
I've just released 1.0.5, please check again! I'm curious to see if this works in 2.1.0 as well, since I'm not actively using spark 2.1.0 at work at this moment.

**Comment by quartox** [comment]
I am a novice scala user, but I still can't find the spark 2.1.0 version or the 1.0.5 version of sparklint when using `spark-submit` with `--packages com.groupon.sparklint:sparklint-spark202_2.11:1.0.5` or `--packages com.groupon.sparklint:sparklint-spark210_2.11:1.0.5`. On the other hand, `--packages com.groupon.sparklint:sparklint-spark202_2.11:1.0.4` works. 

Based on the module not found warning it is finding the packages from the central maven repositories: https://repo1.maven.org/maven2/com/groupon/sparklint/

The warning mentions a local-m2-cache and local-ivy-cache. I am not sure if the intended use of sparklint is to add the jars to one of these caches.

**Comment by roboxue** [comment]
let me verify the sonatype release status later today...

**Comment by roboxue** [comment]
It took some while for public maven to sync with sonatype, but it is there right now. Please try again and let me know

**Comment by quartox** [comment]
It found the package, but I it doesn't parse the logs while the job is running. I will open another issue.
